### ISSUE TITLE
First Release

### ISSUE THREAD

**Issue by kemitchell** [berneout/big-time-public-license#6]
@mattt, @elavoie, I've published a first prerelease here: https://github.com/berneout/big-time-public-license/releases/tag/v1.0.0-pre.1 It incorporates all my latest thoughts and outside feedback.

If you have time, I'd greatly appreciate your thoughts. You might like to just paste the text into a new issue, quote it, and then add your thoughts and questions as you read, like you're replying to an e-mail.

Of course, you're also welcome to reach me by e-mail.

**Comment by elavoie** [comment]
@kemitchell Looks good to me, addresses all my needs.

**Comment by kemitchell** [comment]
@elavoie thoughts on the name?

**Comment by elavoie** [comment]
@kemitchell I think Big Time license suggests that those who "succeed" and have the means to do so pay, so that seems appropriate to me!

**Comment by kemitchell** [comment]
https://bigtimelicense.com/

**Comment by mattt** [comment]
@kemitchell Thanks so much for putting this together, and for reaching out to me for comment. (Apologies for the late response!)

This couldn't have come at a better time, as I'm planning to launch a self-hosted software product early next year, and have been looking for licensing terms that strike a balance between open source ideals and economic realities. I think this license offers a compelling vision for what this can look like.

As with your other work, I very much like the accessible, plain language used here. I also really like how qualifications for being a Small Business are delegated to the federal standard.   Here are some notes I had while reviewing the 1.0.0-pre.2 version of this document:

- Under **Purpose**:  

> These terms let individuals, nonprofit organizations, and fledgling companies use and share this software for free, while also guaranteeing paid licenses for others will be available on fair terms.

  I appreciate the use of the term "fledgling" instead of the (now pretty much meaningless) "startup", however it struck me as unintentionally having a slightly negative connotation. Searching the web, I found this definition from the  [Cambridge Business English Dictionary](https://dictionary.cambridge.org/us/dictionary/english/fledgling):
 
>> a fledgling company or industry is a fairly new one with little experience in a business activity  	

A business may operate successfully for many years at a small scale in a way that qualifies as a Small Business, but not a "fledgling company". It may be worth investigating an alternative to set the tone for the rest of the document. 

- Under **Notices**: 

> [...] as well as copies of any plain-text lines beginning with Required Notice: that the licensor provided with the software.

  After reading this a few times, I'm not entirely clear on what that means in practice. Is this analogous to the kinds of copyright notices that are required by most OSS licenses? 

- Under **How to Request**:  

> If you can’t deliver a request that way, or this software doesn’t include any addressees, spend one hour online researching an address, recording all your searches and inquiries as you go, and try any addresses that you find.  

I like the time-boxed approach for seeking out a viable address. One hypothetical that came to mind: If, shortly after starting your online search, you found a press release from the licensor company announcing their dissolution (or something to the effect of demonstrating that any attempted request would go unanswered). What would your obligations be under these circumstances?

---

One last thing — I'd be interested to hear your thoughts on how you'd anticipate this license being used to distribute software. 

I don't intend for this to sound like a solicitation of legal advice (and perhaps the answer is indeed "hire a lawyer"), but I think it'd be helpful for adoption if folks coming from an open source background understood how this relates to the standard practice of licensing under MIT, Apache-2, etc. For instance, if someone were to adopt this license for their project, would they have any obligation or incentive to mention "Big Time Public License" in any way?

**Comment by kemitchell** [comment]
@mattt:

I agree with your reservations on "fledgling". You also traced my path there: I wanted to avoid "startup", since that invokes a funding model that will often disqualify from free use under the terms.

The Notices section is indeed a substitute for traditional copyright-notice requirements. It's designed to be easier to administer: `fgrep -r "Required Notice:"`. But if the wording isn't coming through clearly to you, we should improve it.

The terms aren't specific about what to do if you find notice of a resolution or wind-down. But I'd offer that winding a business down doesn't necessarily mean its IP assets evaporate. Sometimes they're liquidated. Sometimes they're transferred out to founders. Sometimes nobody bothers to put them in any particular legal place, and the work essentially becomes "orphaned". I'd want licensees to spend a little time trying to figure it out.

Your last question on "how to use" is a good one. In general terms, I see this license being used much like MIT or BSD. Paste it into `LICENSE`. Copy it into header comments, or put a short notice and a link there.

**Comment by mattt** [comment]
> The terms aren't specific about what to do if you find notice of a resolution or wind-down. But I'd offer that winding a business down doesn't necessarily mean its IP assets evaporate. Sometimes they're liquidated. Sometimes they're transferred out to founders. Sometimes nobody bothers to put them in any particular legal place, and the work essentially becomes "orphaned". I'd want licensees to spend a little time trying to figure it out.

All great points. I think 1 hour is a reasonable amount of time to spend, even if ultimately unfruitful, just to verify one's obligations. Certainly, any attempt to litigate contingencies here wouldn't be worth the additional complexity.

> Your last question on "how to use" is a good one. In general terms, I see this license being used much like MIT or BSD. Paste it into `LICENSE`. Copy it into header comments, or put a short notice and a link there.

Perfect. Thanks for clarifying.

One last question: Do you intend to submit this license to the [SPDX License List](https://spdx.org/licenses/)?

**Comment by kemitchell** [comment]
@mattt if this license sees significant independent use, it should definitely go to SPDX. But we need to be mindful of their time.

Mostly likely scenario: A bit of work to get us to a 1.0.0. Then a period of adoption and revision, without an SPDX ID. Then perhaps a 2.0.0, and a submission to SPDX.

**Comment by kemitchell** [comment]
@mattt could you open a separate issue on Notices? I'm thinking there's a pretty straightforward solution there.

**Comment by mattt** [comment]
@kemitchell Sure thing! See #7.

**Comment by kemitchell** [comment]
@elavoie, @mattt, just a quick note to let you know that I am about to release a version 1.0.0 of the Big Time License, thanks to feedback here on GitHub and elsewhere.

The only change that feels "major" is that I am going to drop the wage-based cap on what can count as a fair price for a big-company license entirely. The general language on fairness and sticking to publishing pricing will remain. But the license will no longer include a computable cap on pricing.
