### ISSUE TITLE
Clarify Required Notice provision in Notices section

### ISSUE THREAD

**Issue by mattt** [berneout/big-time-public-license#7]
Following up on my [initial feedback for 1.0.0-pre.2](https://github.com/berneout/big-time-public-license/issues/6#issuecomment-565247811), [as requested](https://github.com/berneout/big-time-public-license/issues/6#issuecomment-565253452):

> - Under **Notices**: 
>
>> [...] as well as copies of any plain-text lines beginning with Required Notice: that the licensor provided with the software.
>
>   After reading this a few times, I'm not entirely clear on what that means in practice. Is this analogous to the kinds of copyright notices that are required by most OSS licenses?

**Comment by kemitchell** [comment]
So one approach to this would be to add a line at the top where folks can put their names. Something like an MIT/BSD copyright notice, but called something like "Contributors".

If there are multiple contributors, we have to think about how the paid license works. Ideally, I think, there would be one paid license for the whole project, on the receiving end. Which means contributors need some deal among themselves for how to split. [Cross-License Collaboratives](https://xlcollaborative.com) could work there.

**Comment by kemitchell** [comment]
@mattt, thanks again for your feedback here. I'm sorry. It looks like my first replace should have been to #11!

Your instincts about the notice requirement were correct. And for what it's worth, this approach isn't totally new. It's in most of the [PolyForm](https://polyformproject.org) licenses, too.

The general idea is that instead of having a copyright line _in the license_ that has to change, you can put that information somewhere else. Since it's not entirely clear where that might be, we specify a "magic string" that users can search for in your artifacts, to find out deterministically what they need to include in their notices.
